FROM continuumio/miniconda3:4.3.14

RUN apt-get update \
 && apt-get install -y build-essential

# Install requirements
RUN conda install git nodejs
RUN pip install moldesign==0.8.0rc4 twine

# Finally, install the actual package
ADD . /opt/notebook-molecular-visualization
WORKDIR /opt/notebook-molecular-visualization
