FROM continuumio/miniconda3:4.3.14

# Install requirements
RUN conda install git nodejs

# Finally, install the actual package
ADD . /opt/notebook-molecular-visualization
WORKDIR /opt/notebook-molecular-visualization
